name: Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install -yy libseccomp-dev build-essential
      - name: Install Rust
        id: component
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --color=always --no-deps --all
      - name: Make index.html
        run: |
          echo '<meta http-equiv="Refresh" content="0; url=./task_maker/index.html">' > target/doc/index.html
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: target/doc
