# Testing the release process is a nasty process since release.yml is triggered
# when a release is created. Creating a release will send an email to all the
# users watching the repo. To avoid spamming those uses with "test releases" we
# can manually trigger the build process and simply avoid publishing the
# release.

name: Manual Release Test

on: workflow_dispatch

jobs:
  Linux:
    name: Build & Publish (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build deb file
        run: |
          docker run --rm -v $(pwd):/source ghcr.io/edomora97/task-maker-rust-release-linux
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ubuntu deb
          path: "target/debian/*.deb"
