name: Release

on:
  release:
    types: [created]

jobs:
  Linux:
    name: Build & Publish (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build deb file
        run: |
          docker run --rm -v $(pwd):/source ghcr.io/edomora97/task-maker-rust-release-linux
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "target/debian/*.deb"
      ## For now do not build the docker container for the server/worker: it requires some fixes because the workers
      ## now spawn a single instance instead of as many as cores. Moreover, the server and worker commands changed.
      # - name: Publish docker container
      #   run: |
      #     echo ${DOCKER_PASSWORD} | docker login --username edomora97 --password-stdin
      #     export TM_VERSION=$(grep version Cargo.toml | head -n 1 | cut -d'"' -f 2)
      #     cd tools/docker
      #     docker build --build-arg TM_VERSION=$TM_VERSION -t edomora97/task-maker-rust:latest -t edomora97/task-maker-rust:$TM_VERSION .
      #     docker push edomora97/task-maker-rust:$TM_VERSION
      #     docker push edomora97/task-maker-rust:latest
      #   env:
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
